---
driver:
  name: dokken

transport:
  name: dokken
  username: root

provisioner:
  name: chef_zero
  sudo: false
  install_strategy: skip
  cookbook_path:
    - /opt/kitchen/cookbooks

verifier:
  name: inspec
  chef_license: accept-no-persist

platforms:
  - name: rockylinux-9

suites:
  - name: upload
    verifier:
      inspec_tests:
        - test/integration/upload
